spring.application.name=lab1

spring.datasource.url=jdbc:postgresql://localhost:5432/notes_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=notes_user
spring.datasource.password=notes_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=Y2hhbmdlLXRoaXMtc2VjcmV0LXRvLWEtbG9uZy1yYW5kb20tdmFsdWUtZm9yLWhzMjU2
jwt.expiration-time=86400000
